### PR TITLE
Add items for repairs instead of raw material

### PR DESCRIPTION
**Pull request by Bigbearbeasttv**
need PR from qb-core and qb-crafting to work

### CODE REVIEW

**Comment by Bigbearbeasttv** [comment]
https://github.com/qbcore-framework/qb-core/pull/333

**Comment by Bigbearbeasttv** [comment]
Will also need pr for inventory for images

**Comment by Bigbearbeasttv** [comment]
https://github.com/qbcore-framework/qb-crafting/pull/17

**Comment by Bigbearbeasttv** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/155

**Review by Eralpozcan — APPROVED** [review]

**Review by ItsANoBrainer — APPROVED** [review]

**Pull request closed without merging**
