### PR TITLE
Saving vehicle damage to data base

### PR DESCRIPTION
**Pull request by ImpulseFPS**

### CODE REVIEW

**Comment by zfbx** [comment]
I don't have a current build of qbcore available to me at the moment but what resource handles `vehiclemod:server:saveStatus`?

**Comment by ImpulseFPS** [comment]
> I don't have a current build of qbcore available to me at the moment but what resource handles `vehiclemod:server:saveStatus`?

saves vehicle axel, engine, radiator, brakes, clutch, fuel damages to the player_vehicles tabel

**Comment by zfbx** [comment]
Sorry was on my phone previously, I see now it's actually in this resource, weird and inconsistent naming conventions 🤦 

Anyways, this is in a half second loop, how often does this actually trigger? 100 people all driving around triggering vehicle damage database updates every half second sounds like a really bad time

**Comment by ImpulseFPS** [comment]
Now when you mention it yea it does suck lol

**Pull request closed without merging**
