### PR TITLE
replace Config.Damages by locale

### PR DESCRIPTION
**Pull request by woerki**
It looks a little bit crazy to use locale for Config.ValuesLabels, but use english names for Config.Damages. Both can use same translations - or is there a problem?

BTW: 
- Config.Vehicles
- Config.Businesses
- Config.RepairCost should get a locale variable for translations, too.

### CODE REVIEW

**Comment by ChristianBDev** [comment]
LGTM

**Comment by zwkf** [comment]
Nice. 
It might be even better to remove this from config entirely and put the lang calls directly into the code directly?

**Comment by ChristianBDev** [comment]
> Nice. It might be even better to remove this from config entirely and put the lang calls directly into the code directly?

Will work on this today!

**Comment by ChristianBDev** [comment]
> Nice. It might be even better to remove this from config entirely and put the lang calls directly into the code directly?

Will add another pr pointing to this one!

**Review by ChristianBDev — APPROVED** [review]
LGTM!

**Comment by ChristianBDev** [comment]
> 

The Config.Damages is in the Config? Which then is getting called in the [client/drivingdistance.lua](https://github.com/qbcore-framework/qb-mechanicjob/blob/7d7bb2f61e9d2d73d72adfdad531192580d90bfc/client/drivingdistance.lua)

**Pull request closed without merging**
