### PR TITLE
Add locales, multi locations of it

### PR DESCRIPTION
**Pull request by Christina1734**
miss post ~"~ sorry guys

### CODE REVIEW

**Comment by FrogCF** [comment]
Hi, please could you merge. Check no coding issues found or lua errors.

**Comment by GhostLegionRP** [comment]
i think the language in maybe config is not understandable for everyone. Maybe merge with english translation.

**Comment by amantu-qbit** [comment]
Please do English also; in some places, you didn't use the lang system for translation.

**Comment by amantu-qbit** [comment]
@Christina1734 Please do English also. in some places, you didn't use the lang system for translation.

**Pull request closed without merging**
