### PR TITLE
Create ro.lua

### PR DESCRIPTION
**Pull request by wanderrer**
Romanian translation for qb-mechanicjob

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Review by tom-osborne — CHANGES_REQUESTED** [review]
The locales were implemented in a different PR. Please can you update your labels to match the labels on the main branch.

Many thanks

**Comment by wanderrer** [comment]
I saw it was, but as the new translation dose not include values, for instance in Romanian language the translation won't be accurate or grammatically correct, as I cannot move a value anywhere in the text :) I'm forced to keep the current form.

**Comment by tom-osborne** [comment]
> I saw it was, but as the new translation dose not include values, for instance in Romanian language the translation won't be accurate or grammatically correct, as I cannot move a value anywhere in the text :) I'm forced to keep the current form.

Good point, I did not notice that part. I notice you updated it anyway, is that to suit the current method?

If you still have your code for the translation that includes the value placeholders, can you add them all to a single PR (not one per file) by forking and editing the code. I can then review again.

**Comment by wanderrer** [comment]
Sure, I will take care of it in 5 minutes.

**Pull request closed without merging**
